feat: impl attribute matching
wechat-miniprogram/float-pigment pull request #5
Opened 2024-12-27 13:16 UTC by huanghongxun

2024-12-30 05:06 UTC, LastLeaf commented
Is it required to add an extra type parameter?

2024-12-30 08:29 UTC, TtTRz requested changes
LGTM, thanks for the PR!
But you still need to add some test cases.

2024-12-30 09:49 UTC, huanghongxun commented
> Is it required to add an extra type parameter?

A type parameter allows embedder making its own attribute memory layout. Actually I also wishes making `StyleQuery::classes` generic too.

For example, my embedder setup an Attribute struct with attribute name enumerations to reduce memory footprint.

2024-12-30 11:05 UTC, TtTRz approved these changes
LGTM

2024-12-30 11:12 UTC, TtTRz approved these changes
LGTM

2024-12-31 06:44 UTC, LastLeaf commented
> > Is it required to add an extra type parameter?
> 
> A type parameter allows embedder making its own attribute memory layout. Actually I also wishes making `StyleQuery::classes` generic too.
> 
> For example, my embedder setup an Attribute struct with attribute name enumerations to reduce memory footprint.
> 
> ```rust
> struct Attr {
>    name: AttrName,
>    value: TmplNativeData,
> }
> 
> enum AttrName {
>     Class,
>     Name,
>     EnableFlex,
>     ...
> }
> ```

I think a default implementation is needed for the new type parameter, otherwise it can be weird for clients that does not need attribute matching.

2024-12-31 06:55 UTC, LastLeaf commented
And also, if you wish to use custom layout for node trees, it should better be done through a custom `StyleQuery` type:

```rust
trait StyleQuery {
    type ClassIter: Iterator<Item = (String, Option<NonZeroUsize>)>;
    fn tag_name(&self) -> &str;
    fn classes(&self) -> Self::ClassIter;
    // ...
    fn attribute(&self, name: &str) -> &str;
}
```

2025-01-02 05:15 UTC, huanghongxun commented
> And also, if you wish to use custom layout for node trees, it should better be done through a custom `StyleQuery` type:
> 
> ```rust
> trait StyleQuery {
>     type ClassIter: Iterator<Item = (String, Option<NonZeroUsize>)>;
>     fn tag_name(&self) -> &str;
>     fn classes(&self) -> Self::ClassIter;
>     // ...
>     fn attribute(&self, name: &str) -> &str;
> }
> ```

Refactored code introduces `trait StyleNode` and make `StyleQuery` implement `StyleNode`, which can reduce interface migration.

2025-01-02 11:14 UTC, LastLeaf commented
Are there any new test cases about the new matching logic?

2025-01-07 04:40 UTC, huanghongxun commented
> Are there any new test cases about the new matching logic?

Added in test attribute_selector.

2025-01-08 03:53 UTC, LastLeaf commented
Great! Ready to merge it. It is a significant improvement so the next publish will be 0.3.0.

2025-01-08 03:53 UTC, merged